//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.18 at 11:17:02 PM BST 
//


package com.ttdev.Prueba;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ttdev.Prueba package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ttdev.Prueba
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Prueba.FieldDescripcion.Und.Item }
     * 
     */
    public Prueba.FieldDescripcion.Und.Item createPruebaFieldDescripcionUndItem() {
        return new Prueba.FieldDescripcion.Und.Item();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Uid }
     * 
     */
    public Prueba.RdfMapping.Uid createPruebaRdfMappingUid() {
        return new Prueba.RdfMapping.Uid();
    }

    /**
     * Create an instance of {@link Prueba.FieldImagen.Und }
     * 
     */
    public Prueba.FieldImagen.Und createPruebaFieldImagenUnd() {
        return new Prueba.FieldImagen.Und();
    }

    /**
     * Create an instance of {@link Prueba.FieldImagen.Und.Item }
     * 
     */
    public Prueba.FieldImagen.Und.Item createPruebaFieldImagenUndItem() {
        return new Prueba.FieldImagen.Und.Item();
    }

    /**
     * Create an instance of {@link Prueba.FieldImagen }
     * 
     */
    public Prueba.FieldImagen createPruebaFieldImagen() {
        return new Prueba.FieldImagen();
    }

    /**
     * Create an instance of {@link Prueba.FieldDescripcion }
     * 
     */
    public Prueba.FieldDescripcion createPruebaFieldDescripcion() {
        return new Prueba.FieldDescripcion();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Changed }
     * 
     */
    public Prueba.RdfMapping.Changed createPruebaRdfMappingChanged() {
        return new Prueba.RdfMapping.Changed();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Created }
     * 
     */
    public Prueba.RdfMapping.Created createPruebaRdfMappingCreated() {
        return new Prueba.RdfMapping.Created();
    }

    /**
     * Create an instance of {@link Prueba.FieldDescripcion.Und }
     * 
     */
    public Prueba.FieldDescripcion.Und createPruebaFieldDescripcionUnd() {
        return new Prueba.FieldDescripcion.Und();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Title }
     * 
     */
    public Prueba.RdfMapping.Title createPruebaRdfMappingTitle() {
        return new Prueba.RdfMapping.Title();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.CommentCount }
     * 
     */
    public Prueba.RdfMapping.CommentCount createPruebaRdfMappingCommentCount() {
        return new Prueba.RdfMapping.CommentCount();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping }
     * 
     */
    public Prueba.RdfMapping createPruebaRdfMapping() {
        return new Prueba.RdfMapping();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Created.Predicates }
     * 
     */
    public Prueba.RdfMapping.Created.Predicates createPruebaRdfMappingCreatedPredicates() {
        return new Prueba.RdfMapping.Created.Predicates();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Body }
     * 
     */
    public Prueba.RdfMapping.Body createPruebaRdfMappingBody() {
        return new Prueba.RdfMapping.Body();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.CommentCount.Predicates }
     * 
     */
    public Prueba.RdfMapping.CommentCount.Predicates createPruebaRdfMappingCommentCountPredicates() {
        return new Prueba.RdfMapping.CommentCount.Predicates();
    }

    /**
     * Create an instance of {@link Prueba }
     * 
     */
    public Prueba createPrueba() {
        return new Prueba();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Name }
     * 
     */
    public Prueba.RdfMapping.Name createPruebaRdfMappingName() {
        return new Prueba.RdfMapping.Name();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Title.Predicates }
     * 
     */
    public Prueba.RdfMapping.Title.Predicates createPruebaRdfMappingTitlePredicates() {
        return new Prueba.RdfMapping.Title.Predicates();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.LastActivity }
     * 
     */
    public Prueba.RdfMapping.LastActivity createPruebaRdfMappingLastActivity() {
        return new Prueba.RdfMapping.LastActivity();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Body.Predicates }
     * 
     */
    public Prueba.RdfMapping.Body.Predicates createPruebaRdfMappingBodyPredicates() {
        return new Prueba.RdfMapping.Body.Predicates();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Name.Predicates }
     * 
     */
    public Prueba.RdfMapping.Name.Predicates createPruebaRdfMappingNamePredicates() {
        return new Prueba.RdfMapping.Name.Predicates();
    }

    /**
     * Create an instance of {@link Prueba.FieldDescripcion.Und.Item.SafeValue }
     * 
     */
    public Prueba.FieldDescripcion.Und.Item.SafeValue createPruebaFieldDescripcionUndItemSafeValue() {
        return new Prueba.FieldDescripcion.Und.Item.SafeValue();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Changed.Predicates }
     * 
     */
    public Prueba.RdfMapping.Changed.Predicates createPruebaRdfMappingChangedPredicates() {
        return new Prueba.RdfMapping.Changed.Predicates();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Rdftype }
     * 
     */
    public Prueba.RdfMapping.Rdftype createPruebaRdfMappingRdftype() {
        return new Prueba.RdfMapping.Rdftype();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.Uid.Predicates }
     * 
     */
    public Prueba.RdfMapping.Uid.Predicates createPruebaRdfMappingUidPredicates() {
        return new Prueba.RdfMapping.Uid.Predicates();
    }

    /**
     * Create an instance of {@link Prueba.RdfMapping.LastActivity.Predicates }
     * 
     */
    public Prueba.RdfMapping.LastActivity.Predicates createPruebaRdfMappingLastActivityPredicates() {
        return new Prueba.RdfMapping.LastActivity.Predicates();
    }

}
