
package ss;

import ss.p1Impl;
import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2019-04-30T09:07:03.656+01:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
 
public class SimpleService_P1_Server{

    protected SimpleService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new p1Impl();
        String address = "http://localhost:8081/DAW2_SOAP/NewsModifier?wsdl";
        Endpoint.publish(address, implementor);

    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SimpleService_P1_Server();
        System.out.println("Server ready..."); 
        while(true){}
        //Thread.sleep(5 * 60 * 1000); 
        //System.out.println("Server exiting");
        //System.exit(0);
    }
}
